FROM openjdk:21
VOLUME /tmp
EXPOSE 8080
RUN mkdir -p /app

ARG JAR_FILE=build/libs/BartenderToolkit-0.0.1-SNAPSHOT.jar
ARG MYSQL_DB_HOST
ARG MYSQL_DB_PORT
ARG MYSQL_DB_NAME
ARG MYSQL_DB_USERNAME
ARG MYSQL_ROOT_PASSWORD

ENV MYSQL_DB_HOST=mysql
ENV MYSQL_DB_PORT=3306
ENV MYSQL_DATABASE=bartenders-toolkit-db
ENV MYSQL_DB_USERNAME=root
ENV MYSQL_ROOT_PASSWORD=airbus

COPY ${JAR_FILE} /app/BartenderToolkit-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/app/BartenderToolkit-0.0.1-SNAPSHOT.jar"]