version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: BartenderToolkit
      MYSQL_ROOT_PASSWORD: 'airbus'
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/BartenderToolkit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 'airbus'
    ports:
      - "8080:8080"
    depends_on:
      - db