spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bartenders-toolkit-db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: airbus
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update